### ISSUE TITLE
sometime oc can't decode fully from php

### ISSUE THREAD

**Issue by tooodooo** [samurai00/aes_pbkdf2#1]
1.php encode this: {"ret":0,"errcode":0,"ads":[],"weather":{"text":"\u6674","temp":"32","code":"32","pressure":"982.05","humidity":"24","winddirection":"250","windspeed":"20.92"}}

oc just decode: {"ret":0,"errcode":0,"ads":[],"weather":{"text":"\u6674","temp":"32","code":"32","pressure":"982.05","humidity":"24","winddirection":"250","wind
left word is disappear.

if i add "-" between wind and speed: wind-speed or some other letters it is work well.

how to fix it?

2.
function rand_str($length) {
        $s = 'abcdefghijklmnokprstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

should be ....mnopqrst....

**Comment by samurai00** [comment]
Problem is fixed. It seems that the PKCS7 padding was wrong.
